dist: trusty
language: java
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk11
  - openjdk14
cache:
  directories:
    - $HOME/.m2
install:
  - if [ "$TRAVIS_JDK_VERSION" = openjdk7 ]; then jdk_switcher use openjdk8; fi
  - 'download_jdk() { if [ "$TRAVIS_JDK_VERSION" = "$1" ]; then curl -LO -H "Cookie: oraclelicense=accept-securebackup-cookie" "$2" && export JAVA_HOME="$HOME/$TRAVIS_JDK_VERSION" && rm -rf "$JAVA_HOME" && mkdir -p "$JAVA_HOME" && tar -C "$JAVA_HOME" -zxf "$(basename "$2")" --strip=1 && "$JAVA_HOME/bin/java" -version && "$JAVA_HOME/bin/javac" -version; fi; }'
  - download_jdk oraclejdk11 https://download.oracle.com/otn-pub/java/jdk/11.0.11+9/ab2da78f32ed489abb3ff52fd0a02b1c/jdk-11.0.11_linux-x64_bin.tar.gz
  - ./mvnw -V deploy -Dmaven.main.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dmaven.deploy.skip=true -Dmaven.install.skip=true
script:
  - if [ "$TRAVIS_JDK_VERSION" = openjdk8 ] && git config --get remote.origin.url 2>&1 | grep -F https://github.com/zhanhb/thymeleaf-layout-dialect -q && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./mvnw -s .travis/settings.xml deploy; else ./mvnw install; fi
  - if [ "$TRAVIS_JDK_VERSION" = openjdk7 ]; then jdk_switcher use openjdk7; fi
  - if [ "$TRAVIS_JDK_VERSION" = openjdk7 ]; then ./mvnw -Djava.version=1.7 surefire:test; fi
  - if [ "$TRAVIS_JDK_VERSION" = openjdk7 ]; then jdk_switcher use openjdk8; fi
before_cache:
  - ./mvnw build-helper:remove-project-artifact
  - find ~/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf '{}' \; 2>/dev/null
after_success:
  - bash <(curl -s https://codecov.io/bash)
