name: publish

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: 'version of jdk to compile'
        default: "11"
        required: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ github.event.inputs.java-version }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - uses: actions/cache@v2
        env:
          cache-name: maven-dependencies
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.workflow }}
            ${{ env.cache-name }}-
      - name: Maven Release
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          [ -z "$GITHUB_ACTOR" ] || {
            git config --global user.name "$GITHUB_ACTOR"
            git config --global user.email "$(gh api "users/$GITHUB_ACTOR" -q '.email//"\(.id)+\(.login)@users.noreply.github.com"')"
          }
          ./mvnw -B -s .github/settings.xml release:prepare
          ./mvnw -B -s .github/settings.xml release:perform
      - name: Before Cache
        run: |
          ./mvnw build-helper:remove-project-artifact || :
          find ~/.m2/ -type d -name '*-SNAPSHOT' \( -exec rm -rf '{}' \; -prune \)
