name: release

on:
  workflow_dispatch:
    inputs:
      java-version:
        type: choice
        description: java version to work with
        default: '11'
        required: true
        options:
          - '8'
          - '11'
          - '17'
      release:
        description: release version
        required: false
      tag:
        description: git tag
        required: false
      next-version:
        description: next develop version
        required: false
      build-timestamp:
        description: |
          project.build.outputTimestamp in UTC
          format: yyyy-MM-dd'T'HH:mm:ssZ
          sample: 2001-09-17T04:45:52Z
        required: false
      skip-perform:
        type: boolean
        required: false
        description: skip release perform
        default: false

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ github.event.inputs.java-version }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      - uses: actions/cache@v3
        env:
          cache-name: maven-dependencies
        with:
          path: ~/.m2
          key: ${{ env.cache-name }}-${{ github.workflow }}-${{ hashFiles('.github/**', '**/pom.xml') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.workflow }}-
            ${{ env.cache-name }}-
      - name: git config
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: .github/functions.sh git_config
      - name: Release Prepare
        if: github.ref_type == 'branch'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          INPUT_RELEASE: ${{ github.event.inputs.release }}
          INPUT_TAG: ${{ github.event.inputs.tag }}
          INPUT_NEXT_VERSION: ${{ github.event.inputs.next-version }}
          INPUT_BUILD_TIMESTAMP: ${{ github.event.inputs.build-timestamp }}
        run: .github/functions.sh release_prepare
      - name: Release Perform
        if: github.event.inputs.skip-perform != 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: .github/functions.sh release_perform
      - name: Before Cache
        run: |
          ./mvnw -B --color=always build-helper:remove-project-artifact || :
          find ~/.m2/ -type d -name '*-SNAPSHOT' \( -exec rm -rf '{}' \; -prune \)
